dist: xenial
language: python
python: 3.7
install:
  - pip install -e .
branches:
  only: master
cache: 
  directories:
    - $HOME/.cache/pip
    - $VIRTUAL_ENV
jobs:
  include:
    - stage: test
      env: step=TEST
      script: ci/test.sh
    - env: step=LINT
      script: ci/lint.sh
    - env: step=DOCSTYLE
      script: ci/docstyle.sh
